POSTGRES_USER=test_user
POSTGRES_PASSWORD=xzh231
POSTGRES_HOST=localhost
POSTGRES_PORT=25432
POSTGRES_DATABASE=dengue
#
API_UUID=''
API_KEY=''
COPERNICUS_DATA=''
#
HOST_UID=$(id -u)
HOST_GID=$(id -g)
#
RBTMQ_PORT=15672
RBTMQHTTP_PORT=25672
RBTMQAMQP_PORT=35672
RBTMQ_USER=''
RBTMQ_PASSWORD=''
RBTMQ_CONFIG_DIR=''
