name: env-satellite
channels:
  - conda-forge
  - defaults
dependencies:
  - docker-compose #
  - python-dotenv #
  - celery #
  - earthengine-api
  - geoviews
  - imageio
  - make
  - poetry
  - pydrive
  - python=3.9
  - rasterio
  - rasterstats
  - sqlalchemy #
